import json
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageEnhance, ImageFilter, ImageOps


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'assets/image/hq720.jpg'
BLUE_OUTPUT = ROOT / 'assets/image/hq720-blue.png'
SCENE_OUTPUT = ROOT / 'scripts/environment/qifeng-scene.js'
ASCII_SIZE = (320, 180)


def enhance_earth_detail(image):
    width, height = image.size
    earth_mask = Image.new('L', image.size, 0)
    ImageDraw.Draw(earth_mask).polygon([
        (int(width * 0.59), height),
        (width, int(height * 0.22)),
        (width, height),
    ], fill=255)
    earth_mask = earth_mask.filter(ImageFilter.GaussianBlur(radius=max(4, int(width * 0.012))))

    detailed = ImageEnhance.Contrast(image).enhance(1.38)
    detailed = detailed.filter(ImageFilter.UnsharpMask(radius=1.25, percent=145, threshold=3))
    return Image.composite(detailed, image, earth_mask)


def add_earth_rim(image):
    width, height = image.size
    points = []
    for index in range(81):
        progress = index / 80
        points.append((
            width * (0.64 + 0.36 * progress ** 0.72),
            height * (1 - 0.78 * progress),
        ))

    halo = Image.new('L', image.size, 0)
    ImageDraw.Draw(halo).line(
        points,
        fill=92,
        width=max(5, int(width * 0.012)),
        joint='curve',
    )
    halo = halo.filter(ImageFilter.GaussianBlur(radius=max(3, int(width * 0.01))))

    rim = Image.new('L', image.size, 0)
    ImageDraw.Draw(rim).line(
        points,
        fill=208,
        width=max(2, int(width * 0.004)),
        joint='curve',
    )
    rim = rim.filter(ImageFilter.GaussianBlur(radius=0.6))
    return ImageChops.lighter(ImageChops.lighter(image, halo), rim)


def main():
    source = Image.open(SOURCE).convert('L')
    contrast = ImageOps.autocontrast(source, cutoff=1)
    shadow_lift = contrast.point(lambda value: int((value / 255) ** 0.82 * 255))
    shadow_lift = enhance_earth_detail(shadow_lift)
    shadow_lift = add_earth_rim(shadow_lift)

    blue = ImageOps.colorize(
        shadow_lift,
        black='#071738',
        white='#eaf2ff',
    )
    blue.save(BLUE_OUTPUT, optimize=True)

    ascii_map = shadow_lift.resize(ASCII_SIZE, Image.Resampling.LANCZOS)
    values = [max(0, min(255, int(value))) for value in ascii_map.getdata()]
    module = '''// Generated by scripts/environment/generate-qifeng-ascii.py.\n'''
    module += 'export const QIFENG_SCENE = Object.freeze({\n'
    module += "  id: 'qifeng-image-ascii',\n"
    module += "  source: 'assets/image/hq720.jpg',\n"
    module += "  bluePreview: 'assets/image/hq720-blue.png',\n"
    module += "  surface: '#1E40AF',\n"
    module += "  ink: '#ffffff',\n"
    module += f'  width: {ASCII_SIZE[0]},\n'
    module += f'  height: {ASCII_SIZE[1]},\n'
    module += f'  values: Object.freeze({json.dumps(values, separators=(",", ":"))}),\n'
    module += '});\n'
    SCENE_OUTPUT.write_text(module, encoding='utf-8')


if __name__ == '__main__':
    main()
